#!/bin/bash

uid=`id -u`
port=$((uid + 10000))

set -e

if [ ! -f main.db ]; then
    echo "*********************"
    echo "Creating new database"
    echo "Log in using demo@example.test with empty password"
    echo "*********************"
    cat schema.sql demo.sql | sqlite3 main.db
fi

export PERL5LIB=./lib:$PERL5LIB

morbo -l http://`hostname -f`:$port main.pl
